sudo: true
language: php
php:
  - 5.6
  - 7.0
  - 7.1
env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"
    - ES_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.3.zip"
  matrix:
    - SYMFONY="~2.8"
    - SYMFONY="~3.0"
    - SYMFONY="~3.1"
    - SYMFONY="~3.2"
    - SYMFONY="~3.3"
    - SYMFONY="~3.4"
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
  # Container based PHP image ues PHP 5.6.5, once it will be upgraded sudo will be not necessary
  - sudo apt-get install -y oracle-java8-set-default
  - curl -L -o elasticsearch.zip $ES_URL
  - unzip elasticsearch.zip
  - ./elasticsearch-*/bin/elasticsearch -d
before_script:
  - composer require --no-update symfony/symfony:${SYMFONY}
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install --no-interaction --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover=coveralls.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
after_script:
  - travis_retry php vendor/bin/coveralls
