sudo: false
language: php
php:
  - 5.6.6
  - 7.0
  - 7.1
  - hhvm
env:
  global:
    - ES_VERSION="5.0" JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"
  matrix:
    - SYMFONY="~2.8"
    - SYMFONY="~3.0"
    - SYMFONY="~3.1"
matrix:
  allow_failures:
    - php: hhvm
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
  #- sudo apt-get install -y oracle-java8-set-default
  - ES_URL=$(curl -sS "https://esvm-props.kibana.rocks/builds" | jq -r ".branches[\"$ES_VERSION\"].zip")
  - curl -L -o elasticsearch.zip $ES_URL
  - unzip elasticsearch.zip
  - ./elasticsearch-*/bin/elasticsearch -d
before_script:
  - composer require --no-update symfony/symfony:${SYMFONY}
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install --no-interaction --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover=coveralls.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
after_script:
  - travis_retry php vendor/bin/coveralls
