sudo: false
language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
env:
  global:
    - ES_VERSION=6.2.3 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  matrix:
    - SYMFONY="^4.4"
    - SYMFONY="^5.0"
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch -d
before_script:
  - composer require --no-update symfony/framework-bundle:${SYMFONY}
  -  if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer install --no-interaction --prefer-dist
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/,var/cache ./
after_script:
  - travis_retry php vendor/bin/coveralls
